//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notepad.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notepad.NET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.txt)|*.txt|XML Files (*.xml)|*.xml|C# Source Files (*.cs)|*.cs|All Files (*.*)|*.*.
        /// </summary>
        public static string FileFilter {
            get {
                return ResourceManager.GetString("FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FindDlgCancel {
            get {
                return ResourceManager.GetString("FindDlgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match _case.
        /// </summary>
        public static string FindDlgCaseSens {
            get {
                return ResourceManager.GetString("FindDlgCaseSens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string FindDlgDirection {
            get {
                return ResourceManager.GetString("FindDlgDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Down.
        /// </summary>
        public static string FindDlgDown {
            get {
                return ResourceManager.GetString("FindDlgDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Find:.
        /// </summary>
        public static string FindDlgFind {
            get {
                return ResourceManager.GetString("FindDlgFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find _next.
        /// </summary>
        public static string FindDlgFindNext {
            get {
                return ResourceManager.GetString("FindDlgFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string FindDlgTitle {
            get {
                return ResourceManager.GetString("FindDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Up.
        /// </summary>
        public static string FindDlgUp {
            get {
                return ResourceManager.GetString("FindDlgUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Background Color....
        /// </summary>
        public static string MenuBkColor {
            get {
                return ResourceManager.GetString("MenuBkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string MenuCopy {
            get {
                return ResourceManager.GetString("MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu_t.
        /// </summary>
        public static string MenuCut {
            get {
                return ResourceManager.GetString("MenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/_Time.
        /// </summary>
        public static string MenuDateTime {
            get {
                return ResourceManager.GetString("MenuDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string MenuDel {
            get {
                return ResourceManager.GetString("MenuDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Find....
        /// </summary>
        public static string MenuFind {
            get {
                return ResourceManager.GetString("MenuFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find _next.
        /// </summary>
        public static string MenuFindNext {
            get {
                return ResourceManager.GetString("MenuFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find _previous.
        /// </summary>
        public static string MenuFindPrev {
            get {
                return ResourceManager.GetString("MenuFindPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Font....
        /// </summary>
        public static string MenuFont {
            get {
                return ResourceManager.GetString("MenuFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Print....
        /// </summary>
        public static string MenuPrint {
            get {
                return ResourceManager.GetString("MenuPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        public static string MenuRedo {
            get {
                return ResourceManager.GetString("MenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Replace....
        /// </summary>
        public static string MenuReplace {
            get {
                return ResourceManager.GetString("MenuReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string MenuSaveAs {
            get {
                return ResourceManager.GetString("MenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select _All.
        /// </summary>
        public static string MenuSelectAll {
            get {
                return ResourceManager.GetString("MenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Status Bar.
        /// </summary>
        public static string MenuStatusBar {
            get {
                return ResourceManager.GetString("MenuStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Toolbar.
        /// </summary>
        public static string MenuToolbar {
            get {
                return ResourceManager.GetString("MenuToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string MenuUndo {
            get {
                return ResourceManager.GetString("MenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Word Wrap.
        /// </summary>
        public static string MenuWordWrap {
            get {
                return ResourceManager.GetString("MenuWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to the file ?.
        /// </summary>
        public static string MessageFileChanged {
            get {
                return ResourceManager.GetString("MessageFileChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find.
        /// </summary>
        public static string MessageNotFound {
            get {
                return ResourceManager.GetString("MessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text modified.
        /// </summary>
        public static string MessageTextChanged {
            get {
                return ResourceManager.GetString("MessageTextChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No file].
        /// </summary>
        public static string NoFile {
            get {
                return ResourceManager.GetString("NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string OpenFileTitle {
            get {
                return ResourceManager.GetString("OpenFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Replace.
        /// </summary>
        public static string ReplaceDlgReplace {
            get {
                return ResourceManager.GetString("ReplaceDlgReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace _all.
        /// </summary>
        public static string ReplaceDlgReplaceAll {
            get {
                return ResourceManager.GetString("ReplaceDlgReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace _to:.
        /// </summary>
        public static string ReplaceDlgReplaceTo {
            get {
                return ResourceManager.GetString("ReplaceDlgReplaceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string ReplaceDlgTitle {
            get {
                return ResourceManager.GetString("ReplaceDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        public static string SaveFileTitle {
            get {
                return ResourceManager.GetString("SaveFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string TextModified {
            get {
                return ResourceManager.GetString("TextModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string ToolbarBkColor {
            get {
                return ResourceManager.GetString("ToolbarBkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy (Ctrl+C).
        /// </summary>
        public static string ToolbarCopy {
            get {
                return ResourceManager.GetString("ToolbarCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut (Ctrl+X).
        /// </summary>
        public static string ToolbarCut {
            get {
                return ResourceManager.GetString("ToolbarCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete (Del).
        /// </summary>
        public static string ToolbarDel {
            get {
                return ResourceManager.GetString("ToolbarDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find (Ctrl+F).
        /// </summary>
        public static string ToolbarFind {
            get {
                return ResourceManager.GetString("ToolbarFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string ToolbarFont {
            get {
                return ResourceManager.GetString("ToolbarFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New (Ctrl+N).
        /// </summary>
        public static string ToolbarNew {
            get {
                return ResourceManager.GetString("ToolbarNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open (Ctrl+O).
        /// </summary>
        public static string ToolbarOpen {
            get {
                return ResourceManager.GetString("ToolbarOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste (Ctrl+V).
        /// </summary>
        public static string ToolbarPaste {
            get {
                return ResourceManager.GetString("ToolbarPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print (Ctrl+P).
        /// </summary>
        public static string ToolbarPrint {
            get {
                return ResourceManager.GetString("ToolbarPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo (Ctrl+Y).
        /// </summary>
        public static string ToolbarRedo {
            get {
                return ResourceManager.GetString("ToolbarRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace (Ctrl+H).
        /// </summary>
        public static string ToolbarReplace {
            get {
                return ResourceManager.GetString("ToolbarReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save (Ctrl+S).
        /// </summary>
        public static string ToolbarSave {
            get {
                return ResourceManager.GetString("ToolbarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo (Ctrl+Z).
        /// </summary>
        public static string ToolbarUndo {
            get {
                return ResourceManager.GetString("ToolbarUndo", resourceCulture);
            }
        }
    }
}
